LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES:=\
	darkhttpd.c

LOCAL_CFLAGS := -O2 -g

LOCAL_C_INCLUDES += \
	$(LOCAL_PATH)

LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)

LOCAL_MODULE_TAGS := eng

LOCAL_MODULE := darkhttpd

include $(BUILD_EXECUTABLE)
